### ISSUE TITLE
Test fail, missing module

### ISSUE THREAD

**Issue by lusimeon** [studiometa/react-next-starter#3]
Hi there, seems to have an error in test file.

The `resolvePathnameFromRouteName` module seems to be missing since the `3.0.0` version.

This cause the following error in `npm run test` command:
```sh
> project@0.0.0 test /path/to/project
> NODE_ENV=test jest --silent --detectOpenHandles --config ./__tests__/jest.config.js

 FAIL  __tests__/common.test.js
  ● Test suite failed to run

    Cannot find module '../helpers/resolvePathnameFromRouteName' from 'common.test.js'

      11 | const routes = require('../server/routes');
      12 | const assert = require('assert');
    > 13 | const resolvePathnameFromRouteName = require('../helpers/resolvePathnameFromRouteName')
         |                                      ^
      14 |
      15 | beforeAll(async () => {
      16 |   return await server.start(process.env.PORT);

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:230:17)
      at Object.require (common.test.js:13:38)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        7s
```

**Comment by chuck-durst** [comment]
Hi, many changes have been made to the routing system since version 3.0.0 and the tests currently in place no longer reflect the app as it is today. In fact, the test update is a todo that I haven't had time to process yet, my bad... I'll let you know when it's done!
